# Generated by Django 4.1.2 on 2022-11-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_doctor_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="blah"),
        ),
    ]
