# Generated by Django 4.1.2 on 2022-11-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_doctor_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
