# Generated by Django 4.1.2 on 2023-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_department_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="contacts",
            field=models.IntegerField(blank=True, default="add your phone", null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
