# Generated by Django 4.1.2 on 2023-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_doctor_contacts_alter_doctor_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="contacts",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
